apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /todos
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-svc
            port:
              number: 8080
      - path: /webui
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webui.name }}-svc
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}-svc
            port:
              number: 80